name: starship-solana-devnet
version: 1.10.0

chains:
  - id: solana
    name: solana
    numValidators: 1
    ports:
      rpc: 8899
      ws: 8900
      exposer: 8001
      faucet: 9900
    resources:
      cpu: "2.0"
      memory: "4Gi"
      
registry:
  enabled: true
  ports:
    rest: 8081
    grpc: 9091